var searchData=
[
  ['template_0',['template',['../group__extensible-rtti.html#autotoc_md57',1,'Extends Template'],['../classcorelib_1_1is__integral__or__enum.html#autotoc_md80',1,'Helper Variable Template']]],
  ['template_20pattern_1',['CRTP (Curiously Recurring Template Pattern)',['../group__extensible-rtti.html#autotoc_md66',1,'']]],
  ['todo_20list_2',['Todo List',['../todo.html',1,'']]],
  ['tracing_2ehxx_3',['tracing.hxx',['../tracing_8hxx.html',1,'']]],
  ['traits_20hxx_20tt_4',['Type System (&lt;tt&gt;detail/casting/traits.hxx&lt;/tt&gt;)',['../group__casting__detail.html#autotoc_md9',1,'']]],
  ['traits_20module_5',['Type Traits Module',['../group__type__traits.html',1,'']]],
  ['traits_2ehxx_6',['traits.hxx',['../traits_8hxx.html',1,'']]],
  ['tt_20detail_20casting_20adapters_20hxx_20tt_7',['Type-Specific Adapters (&lt;tt&gt;detail/casting/adapters.hxx&lt;/tt&gt;)',['../group__casting__detail.html#autotoc_md12',1,'']]],
  ['tt_20detail_20casting_20cast_20hxx_20tt_8',['Cast Infrastructure (&lt;tt&gt;detail/casting/cast.hxx&lt;/tt&gt;)',['../group__casting__detail.html#autotoc_md13',1,'']]],
  ['tt_20detail_20casting_20forwarding_20hxx_20tt_9',['Forwarding (&lt;tt&gt;detail/casting/forwarding.hxx&lt;/tt&gt;)',['../group__casting__detail.html#autotoc_md10',1,'']]],
  ['tt_20detail_20casting_20isa_20hxx_20tt_10',['Type Checking (&lt;tt&gt;detail/casting/isa.hxx&lt;/tt&gt;)',['../group__casting__detail.html#autotoc_md11',1,'']]],
  ['tt_20detail_20casting_20predicates_20hxx_20tt_11',['Predicate Functors (&lt;tt&gt;detail/casting/predicates.hxx&lt;/tt&gt;)',['../group__casting__detail.html#autotoc_md14',1,'']]],
  ['tt_20detail_20casting_20traits_20hxx_20tt_12',['Type System (&lt;tt&gt;detail/casting/traits.hxx&lt;/tt&gt;)',['../group__casting__detail.html#autotoc_md9',1,'']]],
  ['type_13',['type',['../structcorelib_1_1const__pointer__or__const__ref.html#afb527ec2119938edde0a8fd0f306cc09',1,'corelib::const_pointer_or_const_ref::type'],['../structcorelib_1_1add__lvalue__reference__if__not__pointer.html#af880ad54a2ab3da43261fc2d70f78959',1,'corelib::add_lvalue_reference_if_not_pointer::type'],['../structcorelib_1_1add__const__past__pointer.html#aeacc66eb13489a09028b64b0bf4ffabc',1,'corelib::add_const_past_pointer::type']]],
  ['type_20alias_14',['type alias',['../structcorelib_1_1add__const__past__pointer.html#autotoc_md74',1,'Helper Type Alias'],['../structcorelib_1_1add__lvalue__reference__if__not__pointer.html#autotoc_md76',1,'Helper Type Alias'],['../structcorelib_1_1const__pointer__or__const__ref.html#autotoc_md78',1,'Helper Type Alias']]],
  ['type_20checking_15',['type checking',['../group__extensible-rtti.html#autotoc_md60',1,'Type Checking'],['../group__casting.html#autotoc_md2',1,'Type Checking']]],
  ['type_20checking_20tt_20detail_20casting_20isa_20hxx_20tt_16',['Type Checking (&lt;tt&gt;detail/casting/isa.hxx&lt;/tt&gt;)',['../group__casting__detail.html#autotoc_md11',1,'']]],
  ['type_20classification_17',['Type Classification',['../group__type__traits.html#autotoc_md71',1,'']]],
  ['type_20id_20pattern_18',['Type ID Pattern',['../group__extensible-rtti.html#autotoc_md64',1,'']]],
  ['type_20introspection_19',['Type Introspection',['../group__utility.html#autotoc_md86',1,'']]],
  ['type_20specific_20adapters_20tt_20detail_20casting_20adapters_20hxx_20tt_20',['Type-Specific Adapters (&lt;tt&gt;detail/casting/adapters.hxx&lt;/tt&gt;)',['../group__casting__detail.html#autotoc_md12',1,'']]],
  ['type_20system_20tt_20detail_20casting_20traits_20hxx_20tt_21',['Type System (&lt;tt&gt;detail/casting/traits.hxx&lt;/tt&gt;)',['../group__casting__detail.html#autotoc_md9',1,'']]],
  ['type_20traits_20module_22',['Type Traits Module',['../group__type__traits.html',1,'']]],
  ['type_5fname_23',['type_name',['../group__utility.html#gac24e683d07e76a05c5491d91d32f7557',1,'corelib::type_name()'],['../group__utility.html#ga43a32d577d23e32368394673b286ada8',1,'corelib::type_name(T &amp;&amp;value)']]],
  ['type_5fname_2ecxx_24',['type_name.cxx',['../type__name_8cxx.html',1,'']]],
  ['type_5fname_2ehxx_25',['type_name.hxx',['../type__name_8hxx.html',1,'']]],
  ['type_5ftraits_2ehxx_26',['type_traits.hxx',['../type__traits_8hxx.html',1,'']]],
  ['typeid_27',['typeid',['../classcorelib_1_1rtti_1_1Base.html#a1abfd8c8a18b170bafda1fd1750e0304',1,'corelib::rtti::Base::TypeID()'],['../classcorelib_1_1rtti_1_1Extends.html#a9a0fbb05a3b43eb255a7385d3bcdbde7',1,'corelib::rtti::Extends::TypeID()']]],
  ['types_28',['types',['../group__types.html#autotoc_md82',1,'Floating-Point Types'],['../group__types.html#autotoc_md81',1,'Integer Types'],['../structcorelib_1_1detail_1_1UniquePtrCast.html#autotoc_md16',1,'Member Types'],['../structcorelib_1_1detail_1_1CastInfo_3_01To_00_01From_00_01std_1_1enable__if__t_3_9IsSimpleType_3_01From_01_4_1_1value_01_4_01_4.html#autotoc_md32',1,'Member Types'],['../structcorelib_1_1detail_1_1CastRettyImpl.html#autotoc_md20',1,'Member Types'],['../structcorelib_1_1const__pointer__or__const__ref.html#autotoc_md77',1,'Member Types'],['../structcorelib_1_1detail_1_1CastRettyWrap.html#autotoc_md21',1,'Member Types'],['../structcorelib_1_1add__lvalue__reference__if__not__pointer.html#autotoc_md75',1,'Member Types'],['../structcorelib_1_1add__const__past__pointer.html#autotoc_md73',1,'Member Types'],['../structcorelib_1_1detail_1_1CastRettyWrap_3_01To_00_01FromTy_00_01FromTy_01_4.html#autotoc_md22',1,'Member Types'],['../structcorelib_1_1detail_1_1CastRetty.html#autotoc_md23',1,'Member Types'],['../structcorelib_1_1detail_1_1CastInfo.html#autotoc_md30',1,'Member Types'],['../structcorelib_1_1detail_1_1ValueIsPresent_3_01T_00_01std_1_1enable__if__t_3_01detail_1_1IsNullable_3_01T_01_4_01_4_01_4.html#autotoc_md53',1,'Member Types'],['../structcorelib_1_1detail_1_1ValueIsPresent_3_01std_1_1optional_3_01T_01_4_01_4.html#autotoc_md51',1,'Member Types'],['../structcorelib_1_1detail_1_1ValueIsPresent.html#autotoc_md49',1,'Member Types'],['../structcorelib_1_1detail_1_1SimplifyType_3_01const_01From_01_4.html#autotoc_md46',1,'Member Types'],['../structcorelib_1_1detail_1_1SimplifyType.html#autotoc_md44',1,'Member Types'],['../structcorelib_1_1detail_1_1ConstStrippingForwardingCast.html#autotoc_md37',1,'Member Types']]],
  ['types_20module_29',['Types Module',['../group__types.html',1,'']]],
  ['types_2ehxx_30',['types.hxx',['../types_8hxx.html',1,'']]]
];
